#ifndef PL01_LIB_LIB_H_
#define PL01_LIB_LIB_H_

int quit(int num);
int getargcount();
int getargvalue(int i);
int randomize(int seed);
int getrand();
int timestamp();
int newarray();
int freearray(int arr);
int getarraypos(int arr, int pos);
int setarraypos(int arr, int pos, int value);
int arrayfront(int arr);
int arrayback(int arr);
int arrayempty(int arr);
int arraylen(int arr);
int arraycapacity(int arr);
int arrayclear(int arr);
int arraypush(int arr, int value);
int arraypop(int arr);
int arrayresize(int arr, int size);
int newstring(int size);
int freestring(int str);
int getstringpos(int str, int pos);
int setstringpos(int str, int pos, int c);
int stringlen(int str);
int stringmemlen(int str);
int stringadd(int str1, int str2);
int stringconcat(int dest, int src);
int stringcompare(int str1, int str2);
int stringassign(int dest, int src);
int stringtoint(int str);
int inttostring(int i);
int stringtoreal(int str);
int realtostring(int r);
int read();
int write(int i);
int writeln(int i);
int print(int str);
int println(int str);
int getreal();
int putreal(int r);
int getstd(int fd);
int flush(int file);
int open(int filename, int mode);
int close(int file);
int readfile(int file, int buf, int size, int count);
int writefile(int file, int buf, int size, int count);
int readchar(int file);
int writechar(int file, int c);
int readstring(int file, int str, int num);
int writestring(int file, int str);
int tell(int file);
int seek(int file, int offset, int mode);
int shl(int l, int r);
int shr(int l, int r);
int mod(int l, int r);
int logicand(int l, int r);
int logicor(int l, int r);
int logicnot(int opr);
int inttoreal(int i);
int realtoint(int r);
int realisnan(int r);
int realadd(int l, int r);
int realsub(int l, int r);
int realmul(int l, int r);
int realdiv(int l, int r);
int realless(int l, int r);
int reallesseq(int l, int r);
int realgreat(int l, int r);
int realgreateq(int l, int r);
int realabs(int r);
int realmod(int l, int r);
int realpow(int l, int r);
int realsqrt(int r);
int realmax(int l, int r);
int realmin(int l, int r);
int realexp(int r);
int reallog(int r);
int realsin(int r);
int realcos(int r);
int realtan(int r);
int realasin(int r);
int realacos(int r);
int realatan(int r);
int realsinh(int r);
int realcosh(int r);
int realtanh(int r);
int realasinh(int r);
int realacosh(int r);
int realatanh(int r);
int realceil(int r);
int realfloor(int r);

#endif // PL01_LIB_LIB_H_
