LLVM_LIBS := -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport
LLVM_LIBS += -lLLVMDemangle -lz -lcurses -lm -lxml2
LLVM_LIBS += -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMSymbolize
LLVM_LIBS += -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser
LLVM_LIBS += -lLLVMFuzzMutate -lLLVMCoverage -lLLVMTableGen -lLLVMDlltoolDriver
LLVM_LIBS += -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen
LLVM_LIBS += -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter
LLVM_LIBS += -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser
LLVM_LIBS += -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter
LLVM_LIBS += -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser
LLVM_LIBS += -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter
LLVM_LIBS += -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser
LLVM_LIBS += -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter
LLVM_LIBS += -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter
LLVM_LIBS += -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info
LLVM_LIBS += -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen
LLVM_LIBS += -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo
LLVM_LIBS += -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen
LLVM_LIBS += -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter
LLVM_LIBS += -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen
LLVM_LIBS += -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo
LLVM_LIBS += -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser
LLVM_LIBS += -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler
LLVM_LIBS += -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo
LLVM_LIBS += -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler
LLVM_LIBS += -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc
LLVM_LIBS += -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils
LLVM_LIBS += -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser
LLVM_LIBS += -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter
LLVM_LIBS += -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption
LLVM_LIBS += -lLLVMWindowsManifest -lLLVMX86Disassembler -lLLVMX86AsmParser
LLVM_LIBS += -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter
LLVM_LIBS += -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter
LLVM_LIBS += -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter
LLVM_LIBS += -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget
LLVM_LIBS += -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize
LLVM_LIBS += -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser
LLVM_LIBS += -lLLVMInstCombine -lLLVMBitWriter -lLLVMAggressiveInstCombine
LLVM_LIBS += -lLLVMTransformUtils -lLLVMAnalysis -lLLVMProfileData -lLLVMObject
LLVM_LIBS += -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF
LLVM_LIBS += -lLLVMBitReader
